modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/SuperheroesX-Dev/SuperheroesX/issues"
displayURL="https://minecraft.curseforge.com/projects/superheroes-x"
credits="Tiviacz1337 For Deadpool Skin, anonymous people on NovaSkin for Antman, The Wasp Skin and Aquaman Skins, Mini_Me_Snipe for other textures :D"
authors="minecraftschurli"
[[mods]]
    modId="sx"
    version="${version}"
    displayName="Superheroes X"
    description='''
    This mod adds most of your favorite Marvel and DC Characters.
    '''
    [[dependencies.sx]]
        modId="forge"
        mandatory=true
        versionRange="[${forge_version},)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.sx]]
        modId="minecraft"
        mandatory=true
        versionRange="[${minecraft_version},)"
        ordering="NONE"
        side="BOTH"